# permissions for end users to edit janitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: janitor-editor-role
rules:
- apiGroups:
  - janitor.jelmer.uk
  resources:
  - janitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - janitor.jelmer.uk
  resources:
  - janitors/status
  verbs:
  - get
