
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - janitor.jelmer.uk
  resources:
  - janitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - janitor.jelmer.uk
  resources:
  - janitors/finalizers
  verbs:
  - update
- apiGroups:
  - janitor.jelmer.uk
  resources:
  - janitors/status
  verbs:
  - get
  - patch
  - update
